name: flutter_nfc_kit
description: Provide NFC functionality on Android and iOS, including reading metadata, read & write NDEF records, and transceive layer 3 & 4 data with NFC tags / cards
version: 3.0.2
homepage: "https://github.com/nfcim/flutter_nfc_kit"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6
  json_serializable: ^4.1.0

flutter:
  plugin:
    platforms:
      android:
        package: im.nfc.flutter_nfc_kit
        pluginClass: FlutterNfcKitPlugin
      ios:
        pluginClass: FlutterNfcKitPlugin
